### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by amdmaxe** [cdchris12/UDM-DNS-Fix#10]
I have set up the script on a Debian 11 system. When I run it with customized IPs and passwords, I encounter the following error. I use a local admin as the user on the UDM.

Getting host information...
Creating API session...
Logging into the controller...
Login successful!
Getting a list of clients and IPs...
Traceback (most recent call last):
  File "/home/lokal_admin/UDM-DNS-Fix/./update-udmpro-dns.py", line 239, in <module>
    main()
  File "/home/lokal_admin/UDM-DNS-Fix/./update-udmpro-dns.py", line 206, in main
    for c in get_clients(args.baseurl, args.username, args.password, args.site, args.fixed_only, args.verbose):
  File "/home/lokal_admin/UDM-DNS-Fix/./update-udmpro-dns.py", line 88, in get_clients
    fqdn = build_fqdn(c, networks)
  File "/home/lokal_admin/UDM-DNS-Fix/./update-udmpro-dns.py", line 54, in build_fqdn
    if client['network_id'] in networks:
KeyError: 'network_id'

**Comment by cdchris12** [comment]
I've not seen this issue previously... Can you give me the string you used to launch this script (with the passwords redacted), please?

**Comment by amdmaxe** [comment]
Hi,
I'm using the following string from GitHub.

./update-udmpro-dns.py -b https://172.16.0.1:443 -p <pass> -u <user> -su root -sp <ssh_password> -sa 172.16.0.1 -f -vvv

I'm using a fresh install of Ubuntu 22.04.3 LTS. I installed git and pip to download and install the requirements.
Login via UI is working with <user> and <pass>. Login via SSH is working too with root and the <ssh_password>.
My password are in quotes. For example 'safe123!'

**Comment by Brokenpoet** [comment]
Ran into the exact same error running from the command line as above.  Linux Mint 21.3.
